# Generated by Django 3.1.7 on 2021-02-22 20:18

from django.db import migrations, models
import django.utils.timezone
import shrtnr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('shrt', models.CharField(default=shrtnr.models.default_hashid, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(default=shrtnr.models.tomorrow, verbose_name='expires_at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
        ),
    ]
